### ISSUE TITLE
Incorrect noise scale

### ISSUE THREAD

**Issue by Shua-Kang** [PhungLai728/DP-CL#1]
Hi, something is wrong with the noise scale.
It is the code of adding noise to scale. model.py line 1349
```python
computed_gradient1 += tf.random_normal(shape=tf.shape(computed_gradient1), mean=0.0, stddev = (sigma * sensitivity)**2, dtype=tf.float32)
```
The stddev is the standard deviation. At DP-SGD, standard deviation should be sigma * sensitivity rather than with "**2".
So it should be
```python
computed_gradient1 += tf.random_normal(shape=tf.shape(computed_gradient1), mean=0.0, stddev = (sigma * sensitivity), dtype=tf.float32)
```

**Comment by PhungLai728** [comment]
Thanks for the concern. We have updated it accordingly in DP-CL folder.
